### ISSUE TITLE
Get: ETag handling

### ISSUE THREAD

**Issue by espen42** [enonic/lib-static#13]
- [x] If devmode, overwrite cache either way
- [x] Make a decent content hash from the content (if not already cached)
- [x] Cache the hash by resource name (and last-modified)
- [ ] Cache the body readout too? #12 
- [x] Compare hash with request (If-None-Match? https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) and return `{ status: 304 }` if matching?
- [x] On 200, add header `{ ETag: <hash> }`
- [x] Test
